[package]
name = "carbon-jupiter-limit-order-decoder"
version = { workspace = true }
description = "Jupiter Limit Order Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
