[package]
name = "carbon-jupiter-swap-decoder"
version = "0.5.0"
description = "Jupiter Swap Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
