[package]
name = "carbon-memo-program-decoder"
version = "0.5.0"
description = "Memo Program Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
spl-memo = { workspace = true }
spl-token = { workspace = true }
