[package]
name = "carbon-phoenix-v1-decoder"
version = "0.5.0"
description = "Phoenix V1 Decoder"
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
carbon-macros = { workspace = true }
carbon-proc-macros = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
