[package]
name = "carbon-prometheus-metrics"
version = { workspace = true }
description = "Prometheus Metrics"
license = { workspace = true }
edition = { workspace = true }

[dependencies]
carbon-core = { workspace = true }

async-trait = { workspace = true }
log = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[lib]
crate-type = ["rlib"]
