[package]
name = "carbon-system-program-decoder"
version = { workspace = true }
description = "System Program Decoder"
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
carbon-core = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
spl-token = { workspace = true }
